---
- name: Restart app container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    state: started
    restart_policy: "{{ app_restart_policy }}"
  when: app_container_name is defined
