---
# Application identity and image
app_name: devops-app
docker_image: poparthur/devops-info-service
docker_tag: latest

# Port mapping: host:container (Python app listens on 5000)
app_port: 5000
app_internal_port: 5000

# Docker Compose
compose_project_dir: "/opt/{{ app_name }}"
docker_compose_version: "3.8"

# Container runtime
app_restart_policy: unless-stopped
app_container_name: "{{ app_name }}"
app_env: {}

# Wipe logic: set to true to remove application completely when running with --tags web_app_wipe
# Wipe only:    ansible-playbook deploy.yml -e "web_app_wipe=true" --tags web_app_wipe
# Clean install: ansible-playbook deploy.yml -e "web_app_wipe=true"
web_app_wipe: false
