replicaCount: 2

image:
  repository: poparthur/devops-info-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

serviceAccount:
  create: true
  name: ""

persistence:
  size: 1Gi

pvc:
  enabled: false

deployment:
  enabled: false

rollout:
  enabled: false

secrets:
  username: admin
  password: supersecret
