apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
#      annotations:
#        vault.hashicorp.com/agent-inject: "true"
#        vault.hashicorp.com/role: "myapp-role"
#        vault.hashicorp.com/agent-inject-secret-config: "secret/data/myapp/config"
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
          - name: config-volume
            configMap:
              name: {{ include "myapp.fullname" . }}-config

          - name: data-volume
            persistentVolumeClaim:
              claimName: {{ include "myapp.fullname" . }}-data

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}

        volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: data-volume
            mountPath: /app/data

        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}

        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}

        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-secret
          - configMapRef:
              name: {{ include "myapp.fullname" . }}-env
